# spy data
ticker: SPY
start: 2015-01-01
end: 2025-01-01

# t-stat params
tstat_feature_window: 200

# volatility params
volatility_feature_window: 60

# state labeling params
vol_percentile: 70
vol_window: 252
regime_threshold: 1.5
smoother: 5

# markov chain params
expanding_window_minimum: 500
state_count_minimum: 15

# exposure params
entropy_confidence: 1
tstat_exposure_window: 20
c: 2

# mean reversion params
zscore_window: 20

# momentum params
momentum_window: 60