# spy data
ticker: SPY

# in-sample dates
start: 2008-01-01
end: 2018-01-01

# t-stat params
tstat_feature_window: 200

# volatility params
volatility_feature_window: 60

# state labeling params
vol_percentile: 70
vol_window: 252
regime_threshold: 0.8
smoother: 5

# markov chain params
expanding_window_minimum: 500
state_count_minimum: 15
rolling_window: 500

# exposure params
entropy_confidence: 1
tstat_exposure_window: 20
c: 2

# mean reversion params
zscore_window: 20
long_short_threshold: 0.05
tanh_scaler: 1

# momentum params
momentum_window: 252
momentum_scaler: 0.05

# metrics params
risk_free_rate: 0

# pca params
variance_threshold: 0.9
corr_threshold: 0.85

# plotting params
rolling_sharpe_window: 252

# candidates params:
sharpe_threshold: 0.7
annualized_threshold: 0.05
annualized_start: 2006-01-01
annualized_end: 2008-01-01