# spy data
ticker: SPY

# in-sample dates
start: 2008-01-01
end: 2018-01-01

# full backtest
backtest_start: 2008-01-01
backtest_end: 2026-01-01

# out-of-sample dates
start_eval: 2018-01-01
end_eval: 2026-01-01

# t-stat params
tstat_feature_window: 200

# volatility params
volatility_feature_window: 60

# state labeling params
vol_percentile: 70
vol_window: 252
regime_threshold: 0.8
smoother: 5

# markov chain params
expanding_window_minimum: 500
state_count_minimum: 15
rolling_window: 750

# exposure params
entropy_confidence: 2.0
tstat_exposure_window: 20
c: 2
entropy_mode: 'portfolio_only'

# mean reversion params
zscore_window: 20
long_short_threshold: 0.05
tanh_scaler: 1

# momentum params
momentum_window: 252
momentum_scaler: 0.05

# metrics params
risk_free_rate: 0

# pca params
variance_threshold: 0.9
corr_threshold: 0.85

# plotting params
rolling_sharpe_window: 252

# candidates params:
sharpe_threshold: 0.7
annualized_threshold: 0.05
annualized_start: 2006-01-01
annualized_end: 2008-01-01

# grid_search params:
alt_gammas: [0.5, 0.8, 1.0, 1.2, 1.4, 2.0]
alt_entropy_modes: ['signal_only', 'portfolio_only', 'both']
alt_entropy_windows: [250, 500, 750]

# monte-carlo params:
block_size: 20
n_simulations: 1000